version: '3.4'

services:
  ucu_postgres:
    container_name: ucu_postgres
    image: postgres:13.4
    restart: on-failure
    ports:
      - 7433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ucu-db-data:/var/lib/postgresql/data

  ucu_hazelcast1:
    container_name: ucu_hazelcast1
    image: hazelcast/hazelcast:5.1.5
    restart: on-failure
    ports:
      - 5701:5701
    networks:
      - ucu-hazelcast-network
    environment:
      HZ_CLUSTERNAME: ucu
      HZ_CPSUBSYSTEM_CPMEMBERCOUNT: 3

  ucu_hazelcast2:
    container_name: ucu_hazelcast2
    image: hazelcast/hazelcast:5.1.5
    restart: on-failure
    ports:
      - 5702:5701
    networks:
      - ucu-hazelcast-network
    environment:
      HZ_CLUSTERNAME: ucu
      HZ_CPSUBSYSTEM_CPMEMBERCOUNT: 3

  ucu_hazelcast3:
    container_name: ucu_hazelcast3
    image: hazelcast/hazelcast:5.1.5
    restart: on-failure
    ports:
      - 5703:5701
    networks:
      - ucu-hazelcast-network
    environment:
      HZ_CLUSTERNAME: ucu
      HZ_CPSUBSYSTEM_CPMEMBERCOUNT: 3

  ucu_mongo:
    container_name: ucu_mongo
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  ucu-db-data:
    driver: local

networks:
  ucu-hazelcast-network:
    driver: bridge