version: '3.4'

services:
  ucu_postgres:
    container_name: ucu_postgres
    image: postgres:13.4
    restart: on-failure
    ports:
      - 7433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ucu-db-data:/var/lib/postgresql/data

volumes:
  ucu-db-data:
    driver: local
